# Generated by Django 2.2 on 2022-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empfirstname', models.CharField(max_length=255)),
                ('emplastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('DateofBirth', models.CharField(max_length=255)),
                ('salutation', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('addressFirstLine', models.CharField(max_length=255)),
                ('addressSecondLine', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
